version: '3.9'

services:
  db:
    image: postgres:16
    container_name: data_divas_db
    restart: always
    environment:
      POSTGRES_USER: snow_user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: snow_db
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
